import type { Metadata } from "next";
import Navigation from "@/components/ui/Navigation";
import Logo from "@/components/ui/Logo";

import "@/styles/globals.css";

export const metadata: Metadata = {
	title: "The Wild Oasis",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en">
			<body className="bg-primary-950 text-primary-100 min-h-screen">
				<Logo />
				<Navigation />
				<main>{children}</main>
				<footer>Copyright by the Wild Oasis</footer>
			</body>
		</html>
	);
}
